services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=JO!hXRhtoM#qh5*YRGT6guBJ4UDr
      - POSTGRES_HOST=production.czoes6484ihj.us-east-2.rds.amazonaws.com
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=JO!hXRhtoM#qh5*YRGT6guBJ4UDr
      - POSTGRES_HOST=production.czoes6484ihj.us-east-2.rds.amazonaws.com
    depends_on:
      - db
